### ISSUE TITLE
FluidContainer missing texture

### ISSUE THREAD

**Issue by o7ux** [Notenoughmail/KubeJS-TFC#17]
My item has a texture without the FluidContainer attribute, but when given the attribute it looses its texture.

Without FluidContainer:
![RHe04Xo](https://github.com/user-attachments/assets/b6c2b32d-8c9c-40c0-b62a-87ea21eab289)

With FluidContainer:
![FFTx6cZ](https://github.com/user-attachments/assets/959507c1-0b15-4060-b494-188070a89a2b)

Textures:
![qrthzrB](https://github.com/user-attachments/assets/e3fa3d03-b586-4f78-9873-026cabfb7ff5)

I also cannot figure out how to make the container drinkable, it will store liquids in the untextured state but i am unable to drink them. I can drink my custom fluid out of other containers and have set that up properly, so it is not an issue with the lemonade.
![Hd9QCxR](https://github.com/user-attachments/assets/fa7f2579-26f0-4a2c-a1b5-935f38074192)

**Comment by o7ux** [comment]
heres the versions i am running as that is probably important 😃
![image](https://github.com/user-attachments/assets/e364d117-00bc-4f33-be6a-d8ff3cf894c2)

**Comment by Notenoughmail** [comment]
Currently, there is no way to make an item that can be drunk from, guess I overlooked that, you'll be able to do that with either the `tfc:jug` or `tfc:glass_bottle` item type in the next version (1.2.3)

As for the textures, they are currently hardcoded to the item's id, which will also be fixed in the next version, for now your textures will have to at `assets/fritzfood/textures/item/item/soda_cup` and `assets/fritzfood/textures/item/item/soda_cup_overlay`

also concerning that the autogenerated filled name isn't working properly, I'll also look into that

**Comment by FritzLehwalder** [comment]
autogenerated fill name is working, just was not in the code at the time
